# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'windows-2019'

steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '../covid-ui'
  
  - task: Npm@1
    displayName: 'npm run build build'
    inputs:
      command: custom
      verbose: false
      workingDir: '../covid-ui'
      customCommand: 'run build'
